- hosts: localhost
  vars:
    sample_vars: software_desing_2018
  tasks:
    - shell: uptime
      register: result

    - debug:
        msg: "{{ result.stdout }}"

    - debug:
        msg: "{{ sample_vars }}"

    - debug:
        msg: "{{ result }}"

    - debug:
        msg: "成功"
      when: result.rc == 0
