- hosts: vagrants
  tasks:
    - name: yumモジュールチェック
      shell: rpm -qa | grep yum | wc -l
      args:
        warn: false
      register: yum_check
      ignore_errors: true

    - name: コマンド実行結果チェック1
      debug:
        msg: "yumモジュールの数は{{ yum_check.stdout }}です"
      when: yum_check.stdout == '1'

    - name: コマンド実行結果チェック3
      debug:
        msg: "yumモジュールの数は{{ yum_check.stdout }}です"
      when: yum_check.stdout == '3'


#    - name: 実行結果
#      debug:
#        msg: "{{ yum_check }}"




#  vars:
#    sample_vars: software_desing_2018
#    - shell: uptime
#      register: result
#
#    - debug:
#        msg: "{{ result.stdout }}"
#
#    - debug:
#        msg: "{{ sample_vars }}"
