---
###不完全
- hosts: test
  shell:
    cmd: |
      rpm -q --qf '%{version}-%{release}' {{package_name |quote}}
  register: result
  changed_when: false

- yum:
    name: "{{package_name}}"
    state: latest
  when: result.stdout_lines[0] is version('1.3.0.1.el7', '<')
  become: true